=== necamat/dictionaryWebService/DictionaryWebService/xml/dictionary.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/dictionary.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE dictionary SYSTEM "dictionary.dtd">

    <dictionary>
    ...
    </dictionary>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dictionary (language)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT language (word)*>
<!ATTLIST language
    lg ID #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT word (#PCDATA)>
<!ATTLIST word
    id CDATA #IMPLIED
  >

=== necamat/dictionaryWebService/DictionaryWebService/xml/dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">
<dictionary>
    <language lg="sr">
        <word id="1">kuca</word>
        <word id="2">drvo</word>
        <word id="3">jabuka</word>
    </language>
    <language lg="en">
        <word id="1">house</word>
        <word id="2">wood</word>
        <word id="3">appel</word>
    </language>
    <language lg="fr">
        <word id="1">maison</word>
        <word id="2">bois</word>
        <word id="3">pomme</word>
    </language>
</dictionary>
